---
published: true
pblished: true
layout: post
title: python局部变量内存地址释放疑问的分析
category: python
catalog: true
tags:
  - python
time: '2022.06.02 09:49'
---

# 一、问题背景

遇到了一段代码，如下所示，第一眼的直觉是变量`ins`是一个局部变量，重复调用`test()`函数会反复创建新的实例`ins`。
```
import sys


def test():
    ins = object()
    print(id(ins))


while True:
    test()
```

但实际情况却是在进程运行期间不会创建新的局部变量`ins`。
```shell
140076922921824
140076922921824
140076922921824
140076922921824
```vim

# 二、原因分析
## 2.1 分析引用计数
在上面示例代码中补充一行代码看一下实际的`ins`引用变量计数情况，代码如下所示：
```python
mport sys


def test():
    ins = object()
    print(id(a))
    ref = sys.getrefcount(ins)
    print(f'引用计数: {ref}')


while True:
    test()

```
执行此示例代码的输出结果是：
```shell
139765934961536
引用计数: 2
139765934961536
引用计数: 2
139765934961536
引用计数: 2
```
这里读者可能会产生一个疑问：这里只有变量`ins`引用到object()实例，为什么引用计数是2？  
这个结果是因为调用`sys.getrefcount()`函数的时候会多产生一个引用计数，具体gc的管理机制可以[点这里](https://devguide.python.org/garbage_collector/?highlight=gc)。  
从上面引用计数输出看，实际唯一的一个引用计数就是`ins`变量，那我们删除一下此变量引用后再看`object()`实例id是否发生变化？
```
import sys


def test():
    ins = object() 
    print(id(ins))
    del ins


while True:
    test()
```
执行上述代码看`ins`的实例`ins`的id还是没有发生任何变化，实际输出如下所示。  
这里和我判断的预期情况不一样，我的预期情况是`ins`唯一引用被删除后就会触发`GC`行为，`ins`对应的内存块就会被回收。
```
140306047644512
140306047644512
140306047644512
```
进一步修改示例代码查看实际的实例删除动作是否进行了？  
如下所示，实际执行后可以确认`__del__`确实是执行了，那这样还有一种推测就是每一次创建`ins`实例都是在原有内存中创建出来而导致实例id未发生改变。
```
import sys
import gc

class Son(object):

    def __del__(self):
        print('Deleting instance')


def test():
    ins = Son()
    print(id(ins))


while True:
    test()
```
执行上述代码后的输出结果如下：
```
140221875591104
Deleting instance
140221875591104
Deleting instance
140221875591104
Deleting instance
```

## 2.2 分析字节码
我们换个思路：从字节码入手看是否能看出一些蛛丝马迹。  
使用`python3 -m dis test.py`可以输出python代码对应的字节码信息：
```shell
  1           0 LOAD_CONST               0 (0)
              2 LOAD_CONST               1 (None)
              4 IMPORT_NAME              0 (sys)
              6 STORE_NAME               0 (sys)

  4           8 LOAD_CONST               2 (<code object test at 0x7fece3319a80, file "test.py", line 4>)
             10 LOAD_CONST               3 ('test')
             12 MAKE_FUNCTION            0
             14 STORE_NAME               1 (test)

 10     >>   16 LOAD_NAME                1 (test)
             18 CALL_FUNCTION            0
             20 POP_TOP
             22 JUMP_ABSOLUTE           16

Disassembly of <code object test at 0x7fece3319a80, file "test.py", line 4>:
  5           0 LOAD_GLOBAL              0 (object)
              2 CALL_FUNCTION            0
              4 STORE_FAST               0 (ins)

  6           6 LOAD_GLOBAL              1 (print)
              8 LOAD_GLOBAL              2 (id)
             10 LOAD_FAST                0 (ins)
             12 CALL_FUNCTION            1
             14 CALL_FUNCTION            1
             16 POP_TOP
             18 LOAD_CONST               0 (None)
             20 RETURN_VALUE
```
从上面输出的字节码来看，和`ins`变量相关的只有两处指令操作：  
- `CALL_FUNCTION`: 调用`object()`创建出相关的实例；
- `STORE_FAST`和`LOAD_FAST`: 对`ins`变量进行存取操作。
排查这三个指令对应cpython代码可以确认都是正常的指令调用没有涉及GC相关活动。


# 参考附录
[Puzzled with LOAD_FAST/STORE_FAST of python](https://stackoverflow.com/questions/28088157/puzzled-with-load-fast-store-fast-of-python)
