---
layout: post
title: python urllib内存泄露问题分析
category: python
catalog: true
published: true
tags:
  - python
time: '2023.02.23 12:07:00'
---

# 问题背景
在python2中调用urllib模块会有循环引用没被释放，触发代码如下所示：
```python
import gc
import sys


if sys.version_info.major == 3:
    from urllib import request
    urlopen = request.urlopen
else:
    import urllib2
    urlopen = urllib2.urlopen


gc.collect()
# the unreachable object will be freed if this flag not set
gc.set_debug(gc.DEBUG_SAVEALL)
print("before call urlopen(), the unreachable object len: %s" % len(gc.garbage))

a = urlopen('http://www.google.com')
del a
# check memory on memory leaks
gc.collect()
print("the unreachable object len: %s" % len(gc.garbage))
```
在python2.7执行示例代码可以看到如下输出：
```shell
before call urlopen(), the unreachable object len: 0
the unreachable object len: 21
```
在python3.9执行示例代码可以看到如下输出：
```shell
before call urlopen(), the unreachable object len: 0
the unreachable object len: 0
```

# 参考文献
- [urllib2's urlopen() method causes a memory leak](https://github.com/python/cpython/issues/42012)